### PR TITLE
Update dir structure according to PhpStorm settings repo

### PR DESCRIPTION
**Pull request by pronskiy**
There is a more easy way to share and install templates. You can do it with Settings repositories.
I'm going to write a post on PhpStorm blog about this soon.

### CODE REVIEW

**Comment by BenParizek** [comment]
Oh, nice. I looked into the Export/Import settings functionality but it looked like it was all or nothing so it didn't appear easy to target just the Live Templates file for sharing. I'll test out your PR when I have a chance. Looks a lot easier than what I currently have as instructions.

**Comment by pronskiy** [comment]
Hi @BenParizek! Can I help you with this somehow?

**Comment by pronskiy** [comment]
Published the blog post https://blog.jetbrains.com/phpstorm/2018/10/sharing-code-snippets-in-phpstorm-easy-way/

**Comment by BenParizek** [comment]
This is awesome @pronskiy. I finally got around to reviewing and will be updating all the different settings repos we use to work like this. Thanks for taking the time to share and post the article!

**Pull request merged**
