### PR TITLE
Adding inckvo & incpo options for including with only param

### PR DESCRIPTION
**Pull request by nfourtythree**

### CODE REVIEW

**Comment by nfourtythree** [comment]
@BenParizek have just thought that these could be better as tabbed vars on the original shortcuts. My bad, I was just doing it quickly before I had, had enough coffee.

Although potentially I guess it could be both.

**Comment by BenParizek** [comment]
@nfourtythree Thanks! And thanks for addressing the README as well.

If you've already got this installed as a Settings Repository, resyncing your Settings Repository in PhpStorm should activate these Live Templates.

```
VCS -> Sync Settings -> Merge
```

**Comment by BenParizek** [comment]
@nfourtythree Good point. As they are likely a bit less common to be used, it may be nice to just have them as options in the single command. If you'd like to submit an update, happy to roll with that.

**Comment by nfourtythree** [comment]
@BenParizek for me they are the most common usage! Component ALL THE THINGS, and avoid accidental inheritance. But anyway that is a little beside the point!

I guess the question would it be annoying if it appears every time and you have to tab to it and hit delete? 🤔 

This stuff is difficult because everyone devs a little different.

**Comment by BenParizek** [comment]
@nfourtythree Fair!

I believe the goal of these snippets should be to default to use cases where folks can expand vs. default to use cases where people way always need to subtract. I think your initial commit addresses that and folks can always add their own Live Templates if they really prefer a particular style that the base doesn't support. Why don't we roll with it for a bit and if you feel you are always reaching for the opposite, you can submit another pull request down the road.

**Pull request merged**
